### PR TITLE
Fix AttributeError on AC registration after gehomesdk 2026.5 rename

### PR DESCRIPTION
**Pull request by DaveZheng**
## Bug

After updating to `gehomesdk` 2026.5 my Built-In AC units (AJCQ12AWHK1 and AJCQ08AWHK1) stopped registering in HA correctly.

Sensors and control greyed out and became unavailable:
bricked_ac_units

 From `update_coordinator` in HA ha_gehome logs:

```
File "/config/custom_components/ge_home/devices/biac.py", line 30, in get_all_entities
    GeErdSensor(self, ErdCode.WAC_DEMAND_RESPONSE_STATE, entity_category=EntityCategory.DIAGNOSTIC),
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'ErdCode' has no attribute 'WAC_DEMAND_RESPONSE_STATE'. Did you mean: 'RESOURCE_DEMAND_RESPONSE_STATE'?
```

Followed about 10 seconds later by:

```
custom_components.ge_home.update_coordinator: Timeout waiting for initial appliance updates
```

Tried clean installing, re-authing, etc, with similar errors

## Cause

gehomesdk simbaja/gehome@3185b34 (2026-05-26, "added resource ERD codes (e.g. power/water usage)") renamed the demand-response codes:

- `WAC_DEMAND_RESPONSE_STATE` (`0xd006`) became `RESOURCE_DEMAND_RESPONSE_STATE` (same address, same enum payload).
- `WAC_DEMAND_RESPONSE_POWER` (`0xd005`) became `RESOURCE_DSM_POWER_USAGE` (same address, but the value is now a 22-byte multi-field struct with `instantaneous_power_w`, `watt_seconds_since_clear`, etc, not a scalar).

The rename itself is good, those codes are cross-appliance DSM / metering, not WAC-specific, but no deprecation aliases were left behind on `ErdCode`, so anything referencing the old names by attribute fails on import.

## Fix

Shimmed the rename in `biac.py` and `wac.py`: look up whichever name the installed SDK has:

```python
_DEMAND_RESPONSE_STATE = (
    getattr(ErdCode, "RESOURCE_DEMAND_RESPONSE_STATE", None)
    or getattr(ErdCode, "WAC_DEMAND_RESPONSE_STATE", None)
)
_DEMAND_RESPONSE_POWER = getattr(ErdCode, "WAC_DEMAND_RESPONSE_POWER", None)
```

Works on any SDK from 2026.2 onward, `manifest.json` untouched. Nobody whose integration was working yesterday gets force-upgraded.

The power sensor gets the same shim treatment. There's no scalar replacement at `0xd005` on the new SDK (it's now a struct), so old-SDK users keep the sensor exactly as before, and new-SDK users won't have it until someone writes a small wrapper around `ErdDsmPowerUsage.instantaneous_power_w`. Happy to send that follow-up if anyone wants it.

## Verified

With the patch:

- `AttributeError` gone from logs
- "Timeout waiting for initial appliance updates" gone
- Able to read and control the GE Units, no more `unavailable` messaging
image

## SDK follow-up

A one-line alias on `ErdCode` in `simbaja/gehome` (e.g. `WAC_DEMAND_RESPONSE_STATE = RESOURCE_DEMAND_RESPONSE_STATE`) would have made this transparent to every downstream consumer. Worth a separate PR there for any community integrations that quietly broke at the same time.

### CODE REVIEW

**Comment by codster303** [comment]
I'm experiencing the same issue. I came to check for info and was going to start working on a fix but you seem to have already got it. Thanks.

**Comment by simbaja** [comment]
Instead of doing this, I've changed the manifest to pin the specific SDK version instead of using ">=", this has been released as 2026.2.1 and should resolve the issue.  The pre-release version (2026.5.0-dev0) has already been modified to utilize the new ERD codes and will work without modification.
